### ISSUE TITLE
Further Development

### ISSUE THREAD

**Issue by odinuv** [keboola/java-oracle-exporter#1]
instance password https://github.com/keboola/java-oracle-exporter/blob/master/data/config.json#L7
 https://github.com/keboola/internal/issues/18#issuecomment-399562759

development tasks:
- use proper CSV library e.g. https://commons.apache.org/proper/commons-csv/user-guide.html ?
- either read yaml or have db-extractor-oracle create the config file
- get headers somehow, or maybe leave it as it is and supply them in db-extractor?

**Comment by odinuv** [comment]
i'd see 1. as the safest (i.e. passing SQL query via args or envs i going to break it), and when db oracle ex will use json config file, it'll be the easiest to implement too

**Comment by pivnicek** [comment]
ok, thanks, agreed
